# Exercice 1 : creation de tableaux



In [2]:
import numpy as np

tab = np.array([0,1,2,3,4,5,6,7,8,9])

print("tab = ", tab)

tab =  [0 1 2 3 4 5 6 7 8 9]


In [3]:
tab1 = np.zeros((3,4)) # tableau remplis de zero avec 3 lignes et 4 colonnes

print (tab1)



[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
tab2 = np.ones((3,4)) # le tableau est rempli de 1 maintenant

print(tab2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [5]:
tab3 = np.full((3,4),2) # on utilise np.full

print(tab3)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [6]:
tab4 = np.random.rand(3,4)
print(tab4)

[[0.99367634 0.46851671 0.70321627 0.41993074]
 [0.56017709 0.46099164 0.1953861  0.04834197]
 [0.32191427 0.97945301 0.94436732 0.6138638 ]]


# Exercice 2 : Somme et moyennes

In [7]:
a = np.arange(1,11)
print("le tableau contient comme valeur", a)

le tableau contient comme valeur [ 1  2  3  4  5  6  7  8  9 10]


In [8]:
s = np.sum(a)

print("la somme des valeurs du tableau est :", s)

la somme des valeurs du tableau est : 55


In [9]:
# on calcule maintenant la moyenne du tableau


In [10]:
moyenne = np.mean(a)
print("la moyenne du tableau est ", moyenne)

la moyenne du tableau est  5.5


In [11]:
# pour verifier, on utilise la fonction assert ; cest tout simple


In [12]:
assert moyenne == (1 + 10)/2

In [13]:
# on affiche la valeur pour verifier

In [14]:
print("la valeur est :", moyenne == (1+10)/2)

la valeur est : True


# Exercice 3 : Tableaux d'entiers aleatoire

In [15]:
# on va generer des valeurs aleatoire entre 0 et 9 inclus

In [16]:
aleatoire = np.random.randint(0,10,size = (5,5))
print("les valeurs aleatoire du tableaux sont",aleatoire)

les valeurs aleatoire du tableaux sont [[1 9 4 5 8]
 [5 1 6 3 4]
 [3 1 8 5 3]
 [4 6 7 1 7]
 [8 9 1 6 0]]


In [17]:
# cherchons la valeur maximale et minimale dans mon tableaux

In [18]:
maximum = np.max(aleatoire)
minimum = np.min(aleatoire)

print("les valeurs maximales et minimales sont :", maximum," et ",minimum)

les valeurs maximales et minimales sont : 9  et  0


# Exercice 4 :  Matrice identite et traces

In [19]:
# creation de la matric eidentite

identite = np.eye(4)
print("voici la matrice identite : \n",identite)

voici la matrice identite : 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [20]:
produit = identite @ identite
print(produit)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [21]:
# on verifie maintenant

In [22]:
np.allclose(identite,produit)

True

In [23]:
# on va afficher le resultat ensuite

print(np.allclose(identite,produit))

True


In [24]:
# on calcule la trace de la matrice I

In [25]:
trace_identite = np.trace(identite)

In [26]:
# on affiche la valeur de la trace
print("comme s'est la somme de la trace, dans ce cas, c'est 4 : ", trace_identite)

comme s'est la somme de la trace, dans ce cas, c'est 4 :  4.0


# Exercice 5 - Sommes et moyenes - bis

In [27]:
# creons un tableaux

a = np.arange(1,11)
print("le tableau a pour valeur : ",a)

le tableau a pour valeur :  [ 1  2  3  4  5  6  7  8  9 10]


In [28]:
# calculons la somme du tableau


In [29]:
somme = np.sum(a)
print("la somme du tableau vaut : ", somme)

la somme du tableau vaut :  55


In [30]:
# calcule de la moyenne du tableau


In [31]:
moyenne = np.mean(a)
print("la moyenne vaut : ",moyenne)

la moyenne vaut :  5.5


In [32]:
# pour verifier, on utilise assert


In [33]:
assert moyenne == (1 + 10)/2

In [34]:
print(moyenne == (1 + 10)/2)

True


# Exercice 6 - Reshape et copie

In [35]:
v = np.arange(12)
print(v)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [36]:
m = v.reshape((3,4))
print(m)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [37]:
# on modifie m(0,0)

m[0,0] = 99

In [38]:
print("la valeur de m est ", m)
print()
print("la valeur de v est ",v)

la valeur de m est  [[99  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

la valeur de v est  [99  1  2  3  4  5  6  7  8  9 10 11]


In [39]:
# on utilise cette fois ci : reshape.copy()



In [40]:
m = v.reshape(3,4).copy()
print(m)

[[99  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [41]:
m[0,0] = 42
print(m)
print()
print(v)

[[42  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[99  1  2  3  4  5  6  7  8  9 10 11]


# Exercice 7 - Tableaux d'entiers aleatoire

In [42]:
# premiere question

In [43]:
b = np.random.randint(0,9,size = (5,5))
print("la valeur du tableau est",b)

la valeur du tableau est [[5 3 3 0 7]
 [0 7 8 2 6]
 [1 8 3 7 8]
 [3 6 3 6 2]
 [1 8 3 1 4]]


In [44]:
maximum = np.max(b)
minimum = np.min(b)
print("la valeur maximale et minimale respectivement sont : ", maximum," et ", minimum)

la valeur maximale et minimale respectivement sont :  8  et  0


# Exercice 8 - Matrice identite et trace

In [45]:
# on va creer la matrice identite

In [46]:
identite = np.eye(4)
print("la matrice identite est : ",identite)

la matrice identite est :  [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [47]:
produit = identite @ identite

print(produit)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [48]:
# enfin on calcule la trace de la matrice identite

trace = np.trace(identite)
print("la trace vaut : ",trace)

la trace vaut :  4.0


# Exercice 9 - Operations elementaires

In [49]:
# on cree deux tableaux .

In [50]:
x = np.array([1,2,3,4,5])
y = np.array([10,20,30,40,50])

print("Voici le tableau x ", x)
print("Voici le tableau y ", y)

Voici le tableau x  [1 2 3 4 5]
Voici le tableau y  [10 20 30 40 50]


In [51]:
# on realise les calculs elementaires

In [52]:
addition = x + y
print(addition)

[11 22 33 44 55]


In [53]:
# go pour la soustraction


In [54]:
soustraction = y - x
print("la soustraction donne ",soustraction)  # sa renvoie un tableau

la soustraction donne  [ 9 18 27 36 45]


In [55]:
# go pour la multiplication element par element.

In [56]:
multiplication = x * y
print("la multiplication element par element donne un tableau : ", multiplication)

la multiplication element par element donne un tableau :  [ 10  40  90 160 250]


In [57]:
# et enfin la division

In [58]:
division = x / y
print(division, "cest mon tableau")

[0.1 0.1 0.1 0.1 0.1] cest mon tableau


In [59]:
# testons la division euclidienne

In [60]:
division_euclidienne = x // y
print(division_euclidienne)

[0 0 0 0 0]


In [61]:
# la racine carree maintenant

In [62]:
sqrt_tab = np.sqrt(y)
print(sqrt_tab) # sa marche

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]


# Exercice 10 - Indexation avancee

In [63]:
# cest parti

In [64]:
m = np.arange(1,17).reshape(4,4)

In [65]:
print("on affiche notre tableau",m)

on affiche notre tableau [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [66]:
# on cree deux tableaux d'indices

In [67]:
ligne = np.array([0,1,2,3])
colonne = np.array([1,2,3,0])
print("ligne = ",ligne,"colonne = ",colonne)

ligne =  [0 1 2 3] colonne =  [1 2 3 0]


In [68]:
indice_selectiones = m[ligne,colonne]

In [69]:
print(indice_selectiones)

[ 2  7 12 13]


In [70]:
# le fancy indexing

In [71]:
v = np.array([5,10,15,20,25])

print("les elements du tableaux sont : ",v)

les elements du tableaux sont :  [ 5 10 15 20 25]


In [72]:
indice_tab = np.array([0,2,4])
print("le sindices du tableaux : ",indice_tab)

le sindices du tableaux :  [0 2 4]


In [73]:
new_tab = v[indice_tab]
print("on recupere les elements qu on souhaite", new_tab)

on recupere les elements qu on souhaite [ 5 15 25]


# Exercice 11 - Operation elementaires (Bis)

In [74]:
x = np.array([1,2,3,4,5])
y = np.array([10,20,30,40,50])

In [75]:
# on effectue les calculs elementaires

In [76]:
somme = x + y
print(somme)

[11 22 33 44 55]


In [77]:
# la soustraction maintenant



In [78]:
soustraction = y - x
print("la soustraction element par element vaut", soustraction)

la soustraction element par element vaut [ 9 18 27 36 45]


In [79]:
# le produit maintenant

In [80]:
produit = x * y
print("le produit element par element vaut", produit)

le produit element par element vaut [ 10  40  90 160 250]


In [81]:
# maintenant la division par reelle


In [82]:
division = x / y
print(division)

[0.1 0.1 0.1 0.1 0.1]


In [83]:
# la racine carree maintenant

In [84]:
racine_caree = np.sqrt(y)
print(racine_caree)

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]


# Exercice 12 - Masques et statistiques conditionelles

In [85]:
# creation du tableau

In [86]:
data = np.random.randint(0,101, size = 100)

print("le tableau data contient comme valeur : ",data)

le tableau data contient comme valeur :  [ 73  25  16  86  47  28  71   9  46   0  47  72  62  42  50  38  51  93
  54  95  95  86  36  81  38  51  69  92  23  16  15  66   6  55  18  76
  18  39  80  16  29   2  97  32  87 100  90   5  85  23  17  58  69  52
  69  98  37  39  53  20  67  21  33  10  89  28  83  94   0  87   6  75
  62  95  53  48  32  49  75  40  70  64   5   7  57  38  60  70  20  78
  44  48  90  53  99  53  77  32  44  21]


In [87]:
# on cree un masque pour reperer les valeurs > 70

In [88]:
mask = data > 70
print(mask)

[ True False False  True False False  True False False False False  True
 False False False False False  True False  True  True  True False  True
 False False False  True False False False False False False False  True
 False False  True False False False  True False  True  True  True False
  True False False False False False False  True False False False False
 False False False False  True False  True  True False  True False  True
 False  True False False False False  True False False False False False
 False False False False False  True False False  True False  True False
  True False False False]


In [89]:
# on extrait les valeurs

In [90]:
hight_val = data[mask]
print("voici les valeurs : ",hight_val)

voici les valeurs :  [ 73  86  71  72  93  95  95  86  81  92  76  80  97  87 100  90  85  98
  89  83  94  87  75  95  75  78  90  99  77]


In [91]:
# on calcule la moyenne et l'ecart type

In [92]:
moyenne = np.mean(hight_val)
print(moyenne)

86.17241379310344


In [93]:
ecart_type = np.std(hight_val)
print(ecart_type)

8.733877621740179


In [94]:
# derniere question

In [95]:
cpt = mask.sum()
print("cpt = ",cpt)


cpt =  29


In [96]:
pourcentage = mask/data.size*100
print("on a le pourcentage ", pourcentage)

on a le pourcentage  [1. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 1. 1. 0. 1.
 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 1. 0. 1. 1. 1. 0.
 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 1. 0. 1.
 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0.
 1. 0. 0. 0.]


# Exercice 13 - Transposition et broadcasting

In [97]:
# on cree la matrice de valeurs aleatoire

In [98]:
m = np.random.rand(4,3)
print(m)

[[0.53048714 0.25965358 0.95888208]
 [0.75621907 0.12083776 0.99531789]
 [0.66073901 0.88046636 0.29420992]
 [0.47191875 0.59395995 0.57057032]]


In [99]:
# creation du vecteur ligne

In [100]:
v = np.full(4,10)
print(v)

[10 10 10 10]


In [101]:
# transposse la matrice

In [102]:
transposee = m.T
print("voici la matrice transposee", transposee)

voici la matrice transposee [[0.53048714 0.75621907 0.66073901 0.47191875]
 [0.25965358 0.12083776 0.88046636 0.59395995]
 [0.95888208 0.99531789 0.29420992 0.57057032]]


In [103]:
# on utilise le broadcasting d enumpy

In [104]:
b = transposee + v
print(b)

[[10.53048714 10.75621907 10.66073901 10.47191875]
 [10.25965358 10.12083776 10.88046636 10.59395995]
 [10.95888208 10.99531789 10.29420992 10.57057032]]


In [105]:
difference = b - transposee
print(difference)

[[10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]]


In [106]:
np.allclose(difference, 10)

True

# Exercice 14 - Creation et manipulation de tableau 2D

In [107]:
# creation de la matrice

In [108]:
a = np.arange(1,26).reshape(5,5)
print("voici ma matrice a ",a)

voici ma matrice a  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [109]:
# l'indexation et le slicing

In [110]:
b = a[:3, :4]

In [111]:
print("voici la matrice extraite : ", b)

voici la matrice extraite :  [[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]]


In [112]:
# recuperer la deuxieme colonee de la matrice a

In [113]:
colonne = a[:,1]
print(colonne)

[ 2  7 12 17 22]


In [114]:
somme_ligne = np.sum(a,axis=1)
print(somme_ligne)

[ 15  40  65  90 115]


In [115]:
moyenne_colonne = np.mean(a, axis = 0)
print(moyenne_colonne)

[11. 12. 13. 14. 15.]


In [116]:
# on utilise un masque.

In [117]:
masque = a > 20
print(masque)
a[masque] = 0
print()
print(a)

[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [ True  True  True  True  True]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [ 0  0  0  0  0]]


# Exercice 15 - Apprehendez Numpy

In [118]:
# creation du tableau

In [119]:
v = np.arange(10)
print("voici mon tableau", v)

voici mon tableau [0 1 2 3 4 5 6 7 8 9]


In [120]:
# on affiche l'element en 4e position

In [121]:
print(v[3])

3


In [122]:
# on affiche les 3 derniers elements du tableaux

In [123]:
print("les 3 derniers elements sont", v[-3:])

les 3 derniers elements sont [7 8 9]


In [124]:
# on va afficher la somme de tout les elements du tableau

In [125]:
somme = np.sum(v)
print("la somme vaut", somme)

la somme vaut 45


In [126]:
# on va afficher la moyenne de v

In [127]:
moyenne = np.mean(v)
print("la moyenne du tableau est : ",moyenne)

la moyenne du tableau est :  4.5


In [128]:
# on multiplie les elets de v par 2

In [129]:
tab = v * 2
print("on a multiplie les elements de v par 2", tab)

on a multiplie les elements de v par 2 [ 0  2  4  6  8 10 12 14 16 18]


# Exercice 16 - Numpy #2

In [130]:
# on cree notre matrice

In [131]:
m = np.arange(1,10).reshape(3,3)
print("voici la forme de ma matrice\n", m)

voici la forme de ma matrice
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [132]:
print("on affiche l'element",m[1,0])

on affiche l'element 4


In [133]:
print("on affiche ", m[:,0])

on affiche  [1 4 7]


In [134]:
print(m[:2,:])

[[1 2 3]
 [4 5 6]]


In [135]:
somme_colones = np.sum(m,axis = 0)
print(somme_colones)

[12 15 18]


In [136]:
# maintenanrt, on s'occupe des lignes


In [137]:
somme_lignes = np.sum(m,axis = 1)
print("la somme des lignes vaut :", somme_lignes)

la somme des lignes vaut : [ 6 15 24]


In [138]:
# obteniur la matrice transposee

In [139]:
transposee = m.T
print("voici la matrice transposee", transposee)

voici la matrice transposee [[1 4 7]
 [2 5 8]
 [3 6 9]]


# Exercice 17 - Numpy #3 

In [140]:
v = np.array([3,1,4,1,5,9])
print("Voici mon tableau v ", v)

Voici mon tableau v  [3 1 4 1 5 9]


In [141]:
# on recupere l'element maximale

In [142]:
maximum = np.max(v)
print("on affiche sa valeur maximale", maximum)

on affiche sa valeur maximale 9


In [143]:
# on utilise argmax pour recuperer sa position

In [144]:
i = np.argmax(v)
print(i)

5


In [145]:
# on trie le tableau en ordre croissant

In [146]:
croissant = np.sort(v)
print("voici mon tableau trie par ordre croissant : ", croissant)

voici mon tableau trie par ordre croissant :  [1 1 3 4 5 9]


In [147]:
# Exericice 18 - Numpy #4

In [148]:
tab = np.array([2,7,1,8,2,8])
print("voici mon tableau", tab)

voici mon tableau [2 7 1 8 2 8]


In [149]:
# le masque boolen



In [150]:
mask = tab > 4
print(mask)

[False  True False  True False  True]


In [151]:
# on affiche la ou s'est true
print(tab[mask])

[7 8 8]


In [152]:
# on eleve les elements du tableaux au carre

In [153]:
carree = np.square(tab)
print(carree)

[ 4 49  1 64  4 64]


In [154]:
# somme du nouveau tableau

In [155]:
somme = np.sum(carree)
print(somme)

186


# Exercice numpy - 4

In [156]:
# creation d'un tableau a une seule dimension

In [157]:
v = np.array([10,20,30,40,50])

print("v = ", v)

v =  [10 20 30 40 50]


In [158]:
# moyenne du tableau

In [159]:
moyenne = np.mean(v)
print("cest la moyenne du tableau :", moyenne)

cest la moyenne du tableau : 30.0


In [160]:
tab = v - moyenne
print(tab)

[-20. -10.   0.  10.  20.]


In [161]:
# ecart type

In [162]:
etype = np.std(v)
print("voici mon ecart type : ", etype)

voici mon ecart type :  14.142135623730951


In [163]:
v_norm = tab / etype
print(v_norm)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


# Exercice Numpy - 5

In [164]:
# on cree la matrice identite

In [165]:
I = np.eye(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [166]:
# on travaille sur la diagonale de la matrice

In [167]:
diagonale = np.array([10,20,30,40])
I[np.diag_indices(4)] = diagonale
print(I)
print("=================")
print(I[np.diag_indices(4)])

[[10.  0.  0.  0.]
 [ 0. 20.  0.  0.]
 [ 0.  0. 30.  0.]
 [ 0.  0.  0. 40.]]
[10. 20. 30. 40.]


In [168]:
# trace de la matrice

In [169]:
trace = np.trace(I)
print(trace)

100.0


In [170]:
# matrice applatie

In [171]:
f = I.flatten()
print(f)

[10.  0.  0.  0.  0. 20.  0.  0.  0.  0. 30.  0.  0.  0.  0. 40.]


# Operation d ebase

In [172]:
# on fazit la somme de deux matrices A et B

In [173]:
A = np.array([[1,2],[3,4]])
print(A)

[[1 2]
 [3 4]]


In [174]:
B = np.array([[0,-1],[5,2]])
print(B)

[[ 0 -1]
 [ 5  2]]


In [175]:
somme_ab = A + B
print(somme_ab)

[[1 1]
 [8 6]]


In [176]:
# un autre calcul matricielle

In [177]:
s = 2 * A - B
print(s)

[[2 5]
 [1 6]]


In [178]:
# produit matriciel
M = A @ B
print(M)

[[10  3]
 [20  5]]


# Exercice 18 - Transposee et trace

In [179]:
# on calcule la transposee de la matrice C

In [180]:
C = np.array([[2,0,1],[-1,3,4]])
print(C)

[[ 2  0  1]
 [-1  3  4]]


In [181]:
transposee = C.T
print(transposee)

[[ 2 -1]
 [ 0  3]
 [ 1  4]]


In [182]:
# trace de la matrice D

In [183]:
D = transposee @ C
print(D)

[[ 5 -3 -2]
 [-3  9 12]
 [-2 12 17]]


In [184]:
trace = np.trace(D)
print(trace)

31


# Exercice 19 - Determinant

In [185]:
tab = np.array([[4,7,2],[0,5,1],[-3,0,6]])
determinant = np.linalg.det(tab)
print(determinant)

128.99999999999997


# Exercice 20 - Inverse et resolution d'un systeme

In [186]:
F = np.array([[1,2,3],[0,1,4],[5,6,0]])
print(F)

[[1 2 3]
 [0 1 4]
 [5 6 0]]


In [187]:
b = np.array([9,7,8])
print(b)

[9 7 8]


In [188]:
# on inverse F.

In [189]:
F_inv = np.linalg.inv(F)
print(F_inv, " ma matrice inversee")

[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]  ma matrice inversee


In [190]:
sol = F_inv @ b
print(sol)

[-50.  43.  -9.]


In [191]:
# on verifie la solution

In [192]:
sol_2 = np.linalg.solve(F,b)
print(sol_2)

[-50.  43.  -9.]


# Exercice 21 - Rang d'une matrice

In [193]:
G = np.array([[1,2,3,4],[2,4,6,8],[0,1,-1,2]])
print(G)

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 0  1 -1  2]]


In [194]:
# maintenant on calcule le rang de la matrice G

In [195]:
rang = np.linalg.matrix_rank(G)
print(rang)

2


# Exercice - 21 - Operation de base (bis) 

In [196]:
# la some matricielle, c'est parti

In [197]:
A = np.array([[1,2],[3,4]])
print(A)

[[1 2]
 [3 4]]


In [198]:
B = np.array([[0,-1],[5,2]])
print(B)

[[ 0 -1]
 [ 5  2]]


In [199]:
# on fait la somme matricielle

In [200]:
C = A + B

In [201]:
print(C)

[[1 1]
 [8 6]]


In [202]:
# autre calcul matricielle

In [203]:
D = 2 * A - B
print(D)

[[2 5]
 [1 6]]


In [204]:
produit_matriciel = A @ B
print(produit_matriciel)

[[10  3]
 [20  5]]


# Exercice 22 - Trnsposee et trace

In [205]:
# calculons la transposee de la matrice C

In [206]:
C = np.array([[2,0,1],[-1,3,4]])
print("voici ma matrice C \n", C)

voici ma matrice C 
 [[ 2  0  1]
 [-1  3  4]]


In [207]:
C_T = C . T
print(C_T,"Il s'agit de la transposee de la matrice C")

[[ 2 -1]
 [ 0  3]
 [ 1  4]] Il s'agit de la transposee de la matrice C


In [208]:
# on calcule la trace de la matrice D

In [209]:
D = C_T @ C
print(D, "Voici la matrice D")

[[ 5 -3 -2]
 [-3  9 12]
 [-2 12 17]] Voici la matrice D


In [210]:
trace = np.trace(D)

In [211]:
print(trace," la trace de la matrice D")

31  la trace de la matrice D


# Exercice 23 - determinant d'une matrice

In [212]:
E = np.array([[4,7,2],[0,5,1],[-3,0,6]])

determinant = np.linalg.det(E)
print(determinant)

128.99999999999997


# Inverse et resolution d'un systeme

In [213]:
I = np.array([[1,2,3],[0,1,4],[5,6,0]])
print(I)

[[1 2 3]
 [0 1 4]
 [5 6 0]]


In [214]:
I_inv = np.linalg.inv(I)

In [215]:
print(I_inv)

[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


In [216]:
b = np.array([9,7,8])
print(b)

[9 7 8]


In [217]:
x = F_inv @ b
print(x)

[-50.  43.  -9.]


In [218]:
sol = np.linalg.solve(F,b)
print(sol)

[-50.  43.  -9.]


# Exercice - 24 - Normes de matrices

In [220]:
A = np.array([[1,-2],[3,0]])
print(A)

[[ 1 -2]
 [ 3  0]]


In [221]:
# premiere question

In [222]:
norme = np.linalg.norm(A)
print("la norme vaut : ",norme)

la norme vaut :  3.7416573867739413


# Vecteurs avec Numpy

# Exercice 25 

In [225]:
v = np.array([1, 2])
w = np.array([-3, 4])

print(v)
print("\n")
print(w)

[1 2]


[-3  4]


In [226]:
somme = v + w
print(somme)

[-2  6]


In [227]:
produit = v - 2 * w
print(produit)

[ 7 -6]


In [228]:
equal = np.array_equal(v+w,w+v)
print(equal)

True


In [229]:
# on veut verifier la distributivite maintenant

In [230]:
distributivite = np.array_equal(2 * (v + w), 2 * v + 2 * w )
print(distributivite)

True


In [231]:
# mais si on avait fait le produit matricielle ?

# Exercice 26 - Produit scalaire et produit vectorielle

In [232]:
u = np.array([1,2,3])
v = np.array([4,5,6])
print("u = ", u)
print("v = ", v)

u =  [1 2 3]
v =  [4 5 6]


In [233]:
# on calcule le produit scalaire.

In [234]:
res = np.dot(u,v)
print("le produit scalaire vaut : ", res)

le produit scalaire vaut :  32


In [235]:
# le produit vectorielle aussi

In [236]:
vectorielle = np.cross(u,v)
print(vectorielle)

[-3  6 -3]


In [ ]:
print("on renvoie un vecteur")